# TenantConfig with multiple hostDevices with/without vniType & vniRange, with multiple networkType: networkId mapping for networkIds
apiVersion: danm.k8s.io/v1
kind: TenantConfig
metadata:
  name: tconf-08
hostDevices:
- name: {{ .Values.infra_int_if }}  
  vniType: vlan
  vniRange: 1000-2000
- name: {{ .Values.infra_ext_if }}  
- name: {{ .Values.infra_storage_if }}  
  vniType: vlan
  vniRange: 2000-3000
networkIds:
  ipvlan:  internal
  flannel: flannel
