# TenantConfig with multiple hostDevices without vniType & vniRange, and with networkType: networkId mapping for networkIds
apiVersion: danm.k8s.io/v1
kind: TenantConfig
metadata:
  name: tconf-06
hostDevices:
- name: {{ .Values.infra_ext_if }}  
- name: {{ .Values.infra_storage_if }}  
networkIds:
  flannel: flannel
