# TenantConfig with one host_device without vniType & vniRange, with networkType: networkId mapping
apiVersion: danm.k8s.io/v1
kind: TenantConfig
metadata:
  name: tconf-02
hostDevices:
- name: {{ .Values.infra_int_if }}  
networkIds:
  ipvlan: internal
