---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: kube-system
  labels:
    app: podinfo
    k8s-app: podinfo
spec:
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    k8s-app: podinfo
    app: podinfo
