apiVersion: apps/v1
kind: Deployment
metadata:
  name: danmnet-pods10
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "clusterNetwork":"cnet-pod1", "ip":"none"
            }
          ]
    spec:
      containers:
      - name: alpine
        image: {{ .Values.registry_url }}:5555/crf/alpine_test:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/dumb-init", "-c", "--"]
        args: ["sleep", "6000"]
