# invalid TenantNetwork manifest with invalid ipv4 route
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-03-02
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    host_device: ens3
    container_prefix: int
    rt_tables: 200
    cidr: 10.240.1.0/24
    routes:
      10.240.1.0/24: 10.240.2.254
