# invalid TenantNetwork manifest with manually defined Alloc 
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-05
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    Alloc: gAAAAAAAAAAAAAAAAAAAAAAA=
    host_device: ens3
    container_prefix: int
    rt_tables: 200
