# invalid TenantNetwork manifest with vxlan defined
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-11
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    host_device: ens3
    container_prefix: int
    rt_tables: 200
    vxlan: 1000
    cidr: 10.240.1.0/24
    allocation_pool:
      start: 10.240.1.100
      end: 10.240.1.200
