# invalid TenantNetwork manifest with AllowedTenants defined
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-09
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  AllowedTenants:
    - default
    - kube-system
    - kube-public
  Options:
    host_device: ens3
    container_prefix: int
    rt_tables: 200
    cidr: 10.240.1.0/24
    allocation_pool:
      start: 10.240.1.100
      end: 10.240.1.200
