# invalid TenantNetwork manifest with allocation_pool defined without ipv4 CIDR
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-06
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    host_device: ens4
    container_prefix: int
    rt_tables: 200
    allocation_pool:
      start: 10.240.1.100
      end: 10.240.1.200
