# invalid TenantNetwork manifest with NetworkID that is longer than 11 characters
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-08
  namespace: default
spec:
  NetworkID: twelve-chars
  NetworkType: ipvlan
  Options:
    host_device: ens3
    container_prefix: int
    rt_tables: 200
    cidr: 10.240.1.0/24
    allocation_pool:
      start: 10.240.1.100
      end: 10.240.1.200
