# invalid TenantNetwork manifest where allocation_pool.end is defined to be smaller than allocation_pool.start
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-invalid-07-01
  namespace: default
spec:
  NetworkID: internal
  NetworkType: ipvlan
  Options:
    host_device: ens3
    container_prefix: int
    rt_tables: 200
    cidr: 10.240.1.0/24
    allocation_pool:
      start: 10.240.1.101
      end: 10.240.1.100
