# valid TenantNetwork manifest with valid ipv4 and ipv6 notation, and with allocation_pool; with ipv4 and ipv6 routes
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-attach-06
  namespace: default
spec:
  NetworkID: tnet06
  NetworkType: ipvlan
  Options:
    host_device: {{ .Values.infra_int_if }}
    container_prefix: int
    rt_tables: 200
    cidr: 10.20.6.0/24
    allocation_pool:
      start: 10.20.6.1
      end: 10.20.6.10
    net6: 2001:db8::/45
