# valid TenantNetwork manifest with valid ipv4 CIDR notation, valid route, and no allocation_pool
apiVersion: danm.k8s.io/v1
kind: TenantNetwork
metadata:
  name: tennet-attach-02
  namespace: kube-system
spec:
  NetworkID: tnet02
  NetworkType: ipvlan
  Options:
    host_device: {{ .Values.infra_int_if }}
    container_prefix: int
    rt_tables: 200
    cidr: 10.240.2.0/24
    allocation_pool:
      start: 10.240.2.2
      end: 10.240.2.6
    routes:
      10.10.2.0/24: 10.240.2.1
