apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-pod6
spec:
  NetworkID: cnet-pod6
  NetworkType: ipvlan
  Options:
    host_device: {{ .Values.infra_int_if }}
    vxlan: 56
    container_prefix: eth1
    rt_tables: 100
    cidr: 10.20.0.0/24
    allocation_pool:
      start: 10.20.0.1
      end: 10.20.0.10