apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-pod7
spec:
  NetworkID: cnet-pod7
  NetworkType: ipvlan
  Options:
    host_device: {{ .Values.infra_int_if }}
    vxlan: 57
    container_prefix: eth2
    rt_tables: 10
    cidr: 10.10.0.0/24
    allocation_pool:
      start: 10.10.0.1
      end: 10.10.0.10