apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  namespace: kube-system
spec:
  containers:
  - name: busybox
    image: registry.kube-system.svc.nokia.net:5555/crf/busybox:latest
    args:
    - sleep
    - "1000"
