apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  namespace: kube-system
spec:
  containers:
  - name: busybox
    image: {{ .Values.registry_url }}:5555/caas/busybox:latest
    args:
    - sleep
    - "1000"
