version: 2.0.0
name: cluster-name

### Cloud description
description: Cloud description

time:
    ntp_servers: [ 10.1.1.2, 10.1.1.3 ]
    zone: Europe/Helsinki

users:
    admin_user_name: cloudadmin
    admin_user_password: "crypted password"
    initial_user_name: um_admin_username
    initial_user_password: um_admin_password
    admin_password: admin_password
