apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-pooling-5
  namespace: default
spec:
  selector:
    matchLabels:
      app: cpu-pooling
  template:
    metadata:
      labels:
        app: cpu-pooling
      annotations:
        nokia.k8s.io/cpus: |
          [{
            "container": "cpu-pooling1",
            "processes":
              [{
                "process": "/usr/bin/dumb-init",
                "args": ["-c", "sleep", "1000"],
                "pool": "exclusive_caas",
                "cpus": {{ .Values.proc_req }}
              }]
          }]
    spec:
      containers:
      - name: cpu-pooling1
        image: {{ .Values.registry_url }}:5555/caas/alpine_test:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/dumb-init", "-c", "--"]
        args: ["sleep", "6000"]
        resources:
          requests:
            nokia.k8s.io/exclusive_caas: {{ .Values.exclusive_pool_req }}
          limits:
            nokia.k8s.io/exclusive_caas: {{ .Values.exclusive_pool_req }}
      - name: cpu-pooling2
        image: {{ .Values.registry_url }}:5555/caas/alpine_test:latest
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do echo \"Test\"; sleep 1; done;"]
        resources:
          requests:
            nokia.k8s.io/shared_caas: {{ .Values.shared_pool_req }}
          limits:
            nokia.k8s.io/shared_caas: {{ .Values.shared_pool_req }}
      nodeSelector:
        nodename: {{ .Values.nodename }}
