apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-invalid-11
spec:
  NetworkID: external
  NetworkType: macvlan
  Options:
    Alloc: gAAAAAAAAAAAAAAAAAAAA=
    host_device: ens3  
    vlan: 500
    container_prefix: ext
    rt_tables: 100
    cidr: 200.0.11.0/16
    allocation_pool:
      start: 200.0.11.0
      end: 200.0.11.255 
