apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-invalid-05
spec:
  NetworkID: external
  NetworkType: ipvlan
  Options:
    host_device: ens3
    vlan: 500
    container_prefix: ext
    rt_tables: 100
    allocation_pool:
      start: 10.100.5.100
      end: 10.100.5.200 
