apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-invalid-08
spec:
  NetworkID: long_cnet-08
  NetworkType: ipvlan
  Options:
    host_device: ens4
    vlan: 500
    container_prefix: ext
    rt_tables: 100
    cidr: 100.100.8.0/24
    allocation_pool:
      start: 100.100.8.0
      end: 100.100.8.255 
