apiVersion: danm.k8s.io/v1 
kind: DanmNet
metadata:
  name: test-net2
  namespace: kube-system
spec:
  NetworkID: test-net2
  Options:
    host_device: {{ .Values.infra_int_if }} 
    cidr: 10.1.1.0/24 
    allocation_pool:
      start: 10.1.1.10
      end: 10.1.1.15
    container_prefix: eth0
    rt_tables: 35
    routes:
      10.1.1.0/32: 10.1.1.1
    vxlan: 50
