apiVersion: apps/v1
kind: Deployment
metadata:
  name: tennet-pod-05
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "tenantNetwork":"tennet-attach-02", "ip":"10.240.3.1"
            }
          ]
    spec:
      containers:
      - name: alpine
        image: {{ .Values.registry_url }}:5555/caas/alpine_test:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/dumb-init", "-c", "--"]
        args: ["sleep", "6000"]
