apiVersion: danm.k8s.io/v1 
kind: DanmNet
metadata:
  name: test-net27
  namespace: kube-system
spec:
  NetworkID: test-net27
  Options:
    host_device: {{ .Values.infra_int_if }} 
    cidr: 10.0.0.0/24 
    allocation_pool:
      start: 10.0.0.1
      end: 10.0.0.20
    container_prefix: eth0
    rt_tables: 10
    vxlan: 61
