apiVersion: v1
kind: Service
metadata:
  labels:
    name: tennet-pod-08
  name: tennet-pod-08
  namespace: default
spec:
  ports:
  - name: tennet-pod-08
    port: 4242
    protocol: TCP
  selector:
    name: tennet-pod-08
