apiVersion: danm.k8s.io/v1 
kind: DanmNet
metadata:
  name: test-net12
  namespace: default
spec:
  NetworkID: test-net12
  Options:
    host_device: ens3 
    cidr: invalid/24 
    allocation_pool:
      start: 10.0.0.1
      end: 10.0.0.20
    container_prefix: eth0
    rt_tables: 19
    vxlan: 55
