apiVersion: danm.k8s.io/v1 
kind: DanmNet
metadata:
  name: test-net3
  namespace: default
spec:
  NetworkID: test-net3
  Options:
    host_device: ens3 
    cidr: 0:0:0:0:0:ffff:0f00:0000/120
    allocation_pool:
      start: 0:0:0:0:0:ffff:0f00:0001
      end: 0:0:0:0:0:ffff:0f00:0014
    container_prefix: eth0
    rt_tables: 12
    vxlan: 51
