apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-06
spec:
  NetworkID: cnet06
  NetworkType: ipvlan
  Options:
    host_device: {{ .Values.infra_ext_if }}  
    vlan: 506
    container_prefix: ext
    rt_tables: 100
    cidr: 10.6.1.0/24
    net6: 2001:db8::/43
    allocation_pool:
      start: 10.6.1.2
      end: 10.6.1.200
    routes:
      10.6.1.0/24: 10.6.1.1
    routes6:
      2001:db8::/43: 2001:db8:1::1
