apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: cnet-08
spec:
  NetworkID: cnet08
  NetworkType: sriov
  Options:
    device_pool: "nokia.k8s.io/sriov_ens3"
    container_prefix: ext
    rt_tables: 100
    cidr: 10.8.1.0/24
    allocation_pool:
      start: 10.8.1.100
      end: 10.8.1.200
